server.port=8084
# Okta Configuration
spring.security.oauth2.client.provider.okta.token-uri=https://trial-6355671.okta.com/oauth2/default/v1/token
spring.security.oauth2.client.registration.okta.client-id=0oatytmf6ibfCNzSP697
spring.security.oauth2.client.registration.okta.client-secret=GtZ_bouZnacNOxFi165-Y3cTGgPxiFOtRt1NPDpIfhu_Z7HBy4h0-j4AupPjoR1u
spring.security.oauth2.client.registration.okta.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.okta.scope=employees.read
okta.oauth2.issuer=https://trial-6355671.okta.com/oauth2/default
employee.api.url=http://localhost:8081