dev.OrgUrl = https://integrator-5922378.okta.com
stg.OrgUrl = https://integrator-5922378.okta.com
prd.OrgUrl = https://integrator-5922378.okta.com

dev.TokenClientCredentials = 00Qa9i6SfpBNAuQk_yO4L3EfjkGixaN4mR0Gfj7ep-
stg.TokenClientCredentials = 00Qa9i6SfpBNAuQk_yO4L3EfjkGixaN4mR0Gfj7ep-
prd.TokenClientCredentials = 00Qa9i6SfpBNAuQk_yO4L3EfjkGixaN4mR0Gfj7ep-

dev.AEGISlinkAppID = 0oay6n4ls99kHfziY697
stg.AEGISlinkAppID = 0oay6n4ls99kHfziY697
prd.AEGISlinkAppID = 0oay6n4ls99kHfziY697

dev.SAMLSetupInstruction = https://trial-6355671.okta.com/app/exksg5ltqnlJn2cDA697/sso/saml/metadata
stg.SAMLSetupInstruction = https://trial-6355671.okta.com/app/exksg5ltqnlJn2cDA697/sso/saml/metadata
prd.SAMLSetupInstruction = https://trial-6355671.okta.com/app/exksg5ltqnlJn2cDA697/sso/saml/metadata