dev.OrgUrl = https://integrator-5922378.okta.com
stg.OrgUrl = https://integrator-5922378.okta.com
prd.OrgUrl = https://integrator-5922378.okta.com

dev.TokenClientCredentials = 00NaPBxu7k8xOBUltQ4NOpK2VaFYwJyXXeJKsNP4yB
stg.TokenClientCredentials = 00NaPBxu7k8xOBUltQ4NOpK2VaFYwJyXXeJKsNP4yB
prd.TokenClientCredentials = 00NaPBxu7k8xOBUltQ4NOpK2VaFYwJyXXeJKsNP4yB

dev.AEGISlinkAppID = 0oay6n4ls99kHfziY697
stg.AEGISlinkAppID = 0oay6n4ls99kHfziY697
prd.AEGISlinkAppID = 0oay6n4ls99kHfziY697
