# PortDev
dev.aegislink.username=aegis1
dev.aegislink.password=Tc3cx5$b3DafLvbr
dev.aegislink.url=jdbc:oracle:thin:@pa-oracledev03:1521:pordev01
dev.aegislink.driverClassName=oracle.jdbc.driver.OracleDriver
dev.aegislink.initialSize=1

# PortUAT
stg.aegislink.username=aegis1
stg.aegislink.password=Tc3cx5$b3DafLvbr
stg.aegislink.url=jdbc:oracle:thin:@nj-oracleuat03:1521:poruat01
stg.aegislink.driverClassName=oracle.jdbc.driver.OracleDriver
stg.aegislink.initialSize=2

# PortProd 
prd.aegislink.username=readonly
prd.aegislink.password=RYzsiQRf6dcc$r6reGHyQ
prd.aegislink.url=jdbc:oracle:thin:@nj-oracleprod05:1521:porprd01
prd.aegislink.driverClassName=oracle.jdbc.driver.OracleDriver
prd.aegislink.initialSize=5