
dev.OrgUrl = https://aegislimiteddev.oktapreview.com
stg.OrgUrl = https://login.uat.aegislink.com
prd.OrgUrl = https://login.aegislink.com

dev.TokenClientCredentials = 00CDiIk9LKyFfeSwNiElw3jFAJ7N3thPFsRbDIfliT
stg.TokenClientCredentials = 005WKbipvEwOV9OwaGTlz6W63lbDcJiaude66Tk4bx
prd.TokenClientCredentials = 00m569wssqJRnZwC8lFAZOi7nOH5U2RASq1E73cign

dev.AEGISlinkAppID = 0oacgpymjzx97EwRg1d6
stg.AEGISlinkAppID = 0oa9r78ldefp693cM1d7
prd.AEGISlinkAppID = 0oa1onxj9wrVrSTRa1d8

dev.SAMLSetupInstruction = https://aegislimiteddev-admin.oktapreview.com/app/aegislimiteddev_aemdevpublish_1/0oacgpymjzx97EwRg1d6/setup/help/SAML_2_0/instructions
stg.SAMLSetupInstruction = https://aegislimiteddev-admin.oktapreview.com/app/aegislimiteddev_aemuatpublish_1/0oa9r78ldefp693cM1d7/setup/help/SAML_2_0/instructions
prd.SAMLSetupInstruction = https://aegislimited-admin.okta.com/app/aegislimited_aegislinkprod_1/0oa1onxj9wrVrSTRa1d8/setup/help/SAML_2_0/instructions